name = "Runner"
uuid = "847b7089-1ebf-4e83-b33e-c3c97d2ccb04"
authors = ["v-i-s-h <get_vichu@yahoo.com> and contributors"]
version = "0.2.0"

[compat]
julia = "1"

[extras]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "ArgParse"]
